site_name: DCS Modding Documentation
theme:
  name: readthedocs

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.blocks.caption
  - toc:
      permalink: "#"

validation:
  absolute_links: ignore
  unrecognized_links: ignore

extra_css:
  - css/extra.css
  # - css/dark.css # Uncomment to use dark mode

nav:
  - Home: index.md
  - Useful Links: links.md
  
  - Aircraft Lua:
    - Stubs:
      - Device Stubs: Aircraft/Lua/Stubs/DeviceStubs.md
      - Mainpanel Stubs: Aircraft/Lua/Stubs/MainPanelStubs.md
      - LockOn_Options: Aircraft/Lua/Stubs/LockOnOptions.md
    - Modules:
      - Terrain: Aircraft/Lua/Modules/Terrain.md
    - Devices:
      - avLuaDevice: Aircraft/Lua/Devices/avLuaDevice.md
      - avSimpleWeaponSystem: Aircraft/Lua/Devices/avSimpleWeaponSystem.md
    - Indicators:
      - Drawing: Aircraft/Lua/Indicators/drawing.md
      - Controllers: Aircraft/Lua/Indicators/controllers.md
    - Plugins:
      - NavDataPlugin: Aircraft/Lua/Plugins/NavDataPlugin.md
      - WeaponSystemPlugin: Aircraft/Lua/Plugins/WeaponSystemPlugin.md
      - LuaToolsPlugin: Aircraft/Lua/Plugins/LuaToolsPlugin.md
  - Aircraft EFM:
    - EFM API: Aircraft/EFM/EFM_API.md
    - Useful Bits: 
      - Prop Blur: Aircraft/EFM/Useful_bits/prop_blur.md
  - Database:
    - wsTypes: Database/wsTypes.md
    - iCommands: Database/iCommands.md
    - Draw Args: Database/draw-args.md
  - Useful bits:
    - Modelviewer: UsefulBits/ModelViewer.md
  - ED Blender Exporter:
      - Overview: EDM-Export/Overview.md
      - Mesh: EDM-Export/Mesh.md
      - Animations: EDM-Export/Animations.md
      - Lights: EDM-Export/Lights.md
  - Beginner's Guide to DCS Modding:
    - Overview: BeginnersGuide/Overview.md
    - 3D Modeling: BeginnersGuide/3DModeling.md 